# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './docs/funcionario/cadastros_funcionario.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CadastrosFuncionario(object):
    def setupUi(self, CadastrosFuncionario):
        CadastrosFuncionario.setObjectName("CadastrosFuncionario")
        CadastrosFuncionario.resize(1000, 650)
        CadastrosFuncionario.setMinimumSize(QtCore.QSize(1000, 650))
        CadastrosFuncionario.setMaximumSize(QtCore.QSize(1000, 650))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./docs/funcionario/imagens/seguro-de-automovel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        CadastrosFuncionario.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(CadastrosFuncionario)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(0, 70, 1001, 45))
        self.groupBox.setStyleSheet("background-color: rgb(166, 159, 159);\n"
"padding-inline:10px;\n"
"border:none;")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.btnSair = QtWidgets.QPushButton(self.groupBox)
        self.btnSair.setGeometry(QtCore.QRect(330, 0, 41, 41))
        self.btnSair.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnSair.setStyleSheet("color: rgb(75, 74, 74);\n"
"font: 14pt \"Segoe UI\";\n"
"text-align: left;")
        self.btnSair.setObjectName("btnSair")
        self.btnVagas = QtWidgets.QPushButton(self.groupBox)
        self.btnVagas.setGeometry(QtCore.QRect(90, 0, 61, 41))
        self.btnVagas.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnVagas.setStyleSheet("color: rgb(75, 74, 74);\n"
"font: 14pt \"Segoe UI\";\n"
"text-align: left;")
        self.btnVagas.setObjectName("btnVagas")
        self.btnHome = QtWidgets.QPushButton(self.groupBox)
        self.btnHome.setGeometry(QtCore.QRect(20, 0, 61, 41))
        self.btnHome.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnHome.setStyleSheet("color: rgb(75, 74, 74);\n"
"font: 14pt \"Segoe UI\";\n"
"text-align: left;")
        self.btnHome.setObjectName("btnHome")
        self.btnEstacionamento = QtWidgets.QPushButton(self.groupBox)
        self.btnEstacionamento.setGeometry(QtCore.QRect(160, 0, 161, 41))
        self.btnEstacionamento.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnEstacionamento.setStyleSheet("color: rgb(75, 74, 74);\n"
"font: 14pt \"Segoe UI\";\n"
"text-align: left;")
        self.btnEstacionamento.setObjectName("btnEstacionamento")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, -5, 1001, 75))
        self.label.setStyleSheet("background-color: rgb(196, 196, 196);\n"
"color: rgb(75, 74, 74);\n"
"font: 24pt \"Segoe UI\";\n"
"padding: 10px;\n"
"border:none;")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 620, 1001, 31))
        self.label_2.setStyleSheet("background-color: rgb(196, 196, 196);\n"
"color: rgb(75, 74, 74);\n"
"")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 130, 151, 31))
        self.label_3.setStyleSheet("color: rgb(75, 74, 74);\n"
"font: 14pt \"Segoe UI\";")
        self.label_3.setObjectName("label_3")
        self.tableCadastros = QtWidgets.QTableWidget(self.centralwidget)
        self.tableCadastros.setGeometry(QtCore.QRect(20, 170, 801, 365))
        self.tableCadastros.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.tableCadastros.setAutoFillBackground(True)
        self.tableCadastros.setStyleSheet("color: rgb(75, 74, 74);")
        self.tableCadastros.setInputMethodHints(QtCore.Qt.ImhNone)
        self.tableCadastros.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableCadastros.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableCadastros.setAlternatingRowColors(True)
        self.tableCadastros.setShowGrid(False)
        self.tableCadastros.setGridStyle(QtCore.Qt.NoPen)
        self.tableCadastros.setWordWrap(True)
        self.tableCadastros.setObjectName("tableCadastros")
        self.tableCadastros.setColumnCount(5)
        self.tableCadastros.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tableCadastros.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tableCadastros.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tableCadastros.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tableCadastros.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tableCadastros.setHorizontalHeaderItem(4, item)
        self.tableCadastros.horizontalHeader().setCascadingSectionResizes(False)
        self.tableCadastros.horizontalHeader().setDefaultSectionSize(160)
        self.tableCadastros.verticalHeader().setVisible(False)
        self.btnNovoCadastro = QtWidgets.QPushButton(self.centralwidget)
        self.btnNovoCadastro.setGeometry(QtCore.QRect(860, 550, 121, 35))
        self.btnNovoCadastro.setMinimumSize(QtCore.QSize(100, 35))
        self.btnNovoCadastro.setMaximumSize(QtCore.QSize(150, 35))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btnNovoCadastro.setFont(font)
        self.btnNovoCadastro.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnNovoCadastro.setStyleSheet("border: none;\n"
"border-radius:10px;\n"
"background-color: rgb(53, 119, 218);\n"
"color: rgb(255, 255, 255);")
        self.btnNovoCadastro.setObjectName("btnNovoCadastro")
        CadastrosFuncionario.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(CadastrosFuncionario)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 22))
        self.menubar.setObjectName("menubar")
        CadastrosFuncionario.setMenuBar(self.menubar)

        self.retranslateUi(CadastrosFuncionario)
        QtCore.QMetaObject.connectSlotsByName(CadastrosFuncionario)

    def retranslateUi(self, CadastrosFuncionario):
        _translate = QtCore.QCoreApplication.translate
        CadastrosFuncionario.setWindowTitle(_translate("CadastrosFuncionario", "Sistema de estacionamento - Cadastros "))
        self.btnSair.setText(_translate("CadastrosFuncionario", "Sair"))
        self.btnVagas.setText(_translate("CadastrosFuncionario", "Vagas"))
        self.btnHome.setText(_translate("CadastrosFuncionario", "Home"))
        self.btnEstacionamento.setText(_translate("CadastrosFuncionario", "Estacionamento"))
        self.label.setText(_translate("CadastrosFuncionario", "Sistema de estacionamento"))
        self.label_2.setText(_translate("CadastrosFuncionario", "Sistema de stacionamento"))
        self.label_3.setText(_translate("CadastrosFuncionario", "Cadastros"))
        item = self.tableCadastros.horizontalHeaderItem(0)
        item.setText(_translate("CadastrosFuncionario", "Nome do cliente"))
        item = self.tableCadastros.horizontalHeaderItem(1)
        item.setText(_translate("CadastrosFuncionario", "CPF"))
        item = self.tableCadastros.horizontalHeaderItem(2)
        item.setText(_translate("CadastrosFuncionario", "Telefone"))
        item = self.tableCadastros.horizontalHeaderItem(3)
        item.setText(_translate("CadastrosFuncionario", "Placa"))
        item = self.tableCadastros.horizontalHeaderItem(4)
        item.setText(_translate("CadastrosFuncionario", "Endereço"))
        self.btnNovoCadastro.setText(_translate("CadastrosFuncionario", "Novo cadastro"))
