# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './docs/funcionario/estacionamento_funcionario.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EstacionamentoFuncionario(object):
    def setupUi(self, EstacionamentoFuncionario):
        EstacionamentoFuncionario.setObjectName("EstacionamentoFuncionario")
        EstacionamentoFuncionario.resize(1000, 650)
        EstacionamentoFuncionario.setMinimumSize(QtCore.QSize(1000, 650))
        EstacionamentoFuncionario.setMaximumSize(QtCore.QSize(1000, 650))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./docs/funcionario/imagens/seguro-de-automovel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        EstacionamentoFuncionario.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(EstacionamentoFuncionario)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(0, 70, 1001, 45))
        self.groupBox.setStyleSheet("background-color: rgb(166, 159, 159);\n"
"padding-inline:10px;\n"
"border:none;")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.btnSair = QtWidgets.QPushButton(self.groupBox)
        self.btnSair.setGeometry(QtCore.QRect(450, 0, 41, 41))
        self.btnSair.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnSair.setStyleSheet("color: rgb(75, 74, 74);\n"
"font: 14pt \"Segoe UI\";\n"
"text-align: left;")
        self.btnSair.setObjectName("btnSair")
        self.btnReservar = QtWidgets.QPushButton(self.groupBox)
        self.btnReservar.setGeometry(QtCore.QRect(350, 0, 91, 41))
        self.btnReservar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnReservar.setStyleSheet("color: rgb(75, 74, 74);\n"
"font: 14pt \"Segoe UI\";\n"
"text-align: left;")
        self.btnReservar.setObjectName("btnReservar")
        self.btnVagas = QtWidgets.QPushButton(self.groupBox)
        self.btnVagas.setGeometry(QtCore.QRect(200, 0, 61, 41))
        self.btnVagas.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnVagas.setStyleSheet("color: rgb(75, 74, 74);\n"
"font: 14pt \"Segoe UI\";\n"
"text-align: left;")
        self.btnVagas.setObjectName("btnVagas")
        self.btnCadastros = QtWidgets.QPushButton(self.groupBox)
        self.btnCadastros.setGeometry(QtCore.QRect(90, 0, 101, 41))
        self.btnCadastros.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnCadastros.setStyleSheet("color: rgb(75, 74, 74);\n"
"font: 14pt \"Segoe UI\";\n"
"text-align: left;")
        self.btnCadastros.setObjectName("btnCadastros")
        self.btnAlugar = QtWidgets.QPushButton(self.groupBox)
        self.btnAlugar.setGeometry(QtCore.QRect(274, 0, 71, 41))
        self.btnAlugar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnAlugar.setStyleSheet("color: rgb(75, 74, 74);\n"
"font: 14pt \"Segoe UI\";\n"
"text-align: left;")
        self.btnAlugar.setObjectName("btnAlugar")
        self.btnHome = QtWidgets.QPushButton(self.groupBox)
        self.btnHome.setGeometry(QtCore.QRect(20, 0, 61, 41))
        self.btnHome.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnHome.setStyleSheet("color: rgb(75, 74, 74);\n"
"font: 14pt \"Segoe UI\";\n"
"text-align: left;")
        self.btnHome.setObjectName("btnHome")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, -5, 1001, 75))
        self.label.setStyleSheet("background-color: rgb(196, 196, 196);\n"
"color: rgb(75, 74, 74);\n"
"font: 24pt \"Segoe UI\";\n"
"padding: 10px;\n"
"border:none;")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 620, 1001, 31))
        self.label_2.setStyleSheet("background-color: rgb(196, 196, 196);\n"
"color: rgb(75, 74, 74);\n"
"")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 130, 161, 31))
        self.label_3.setStyleSheet("color: rgb(75, 74, 74);\n"
"font: 14pt \"Segoe UI\";")
        self.label_3.setObjectName("label_3")
        self.btnMudarStatus = QtWidgets.QPushButton(self.centralwidget)
        self.btnMudarStatus.setGeometry(QtCore.QRect(820, 570, 131, 35))
        self.btnMudarStatus.setMinimumSize(QtCore.QSize(100, 35))
        self.btnMudarStatus.setMaximumSize(QtCore.QSize(150, 35))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btnMudarStatus.setFont(font)
        self.btnMudarStatus.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnMudarStatus.setStyleSheet("background-color: rgb(53, 119, 218);\n"
"color: rgb(255, 255, 255);\n"
"border: none;\n"
"border-radius:10px;")
        self.btnMudarStatus.setObjectName("btnMudarStatus")
        self.lblEstacionamento = QtWidgets.QLabel(self.centralwidget)
        self.lblEstacionamento.setGeometry(QtCore.QRect(40, 180, 911, 371))
        self.lblEstacionamento.setText("")
        self.lblEstacionamento.setPixmap(QtGui.QPixmap("./docs/funcionario/imagens/mapiamento.png"))
        self.lblEstacionamento.setAlignment(QtCore.Qt.AlignCenter)
        self.lblEstacionamento.setObjectName("lblEstacionamento")
        EstacionamentoFuncionario.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(EstacionamentoFuncionario)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 22))
        self.menubar.setObjectName("menubar")
        EstacionamentoFuncionario.setMenuBar(self.menubar)

        self.retranslateUi(EstacionamentoFuncionario)
        QtCore.QMetaObject.connectSlotsByName(EstacionamentoFuncionario)

    def retranslateUi(self, EstacionamentoFuncionario):
        _translate = QtCore.QCoreApplication.translate
        EstacionamentoFuncionario.setWindowTitle(_translate("EstacionamentoFuncionario", "Sistema de estacionamento - Estacionamento"))
        self.btnSair.setText(_translate("EstacionamentoFuncionario", "Sair"))
        self.btnReservar.setText(_translate("EstacionamentoFuncionario", "Reservar "))
        self.btnVagas.setText(_translate("EstacionamentoFuncionario", "Vagas"))
        self.btnCadastros.setText(_translate("EstacionamentoFuncionario", "Cadastros"))
        self.btnAlugar.setText(_translate("EstacionamentoFuncionario", "Alugar"))
        self.btnHome.setText(_translate("EstacionamentoFuncionario", "Home"))
        self.label.setText(_translate("EstacionamentoFuncionario", "Sistema de estacionamento"))
        self.label_2.setText(_translate("EstacionamentoFuncionario", "Sistema de stacionamento"))
        self.label_3.setText(_translate("EstacionamentoFuncionario", "Estacionamento"))
        self.btnMudarStatus.setText(_translate("EstacionamentoFuncionario", "Mudar Status"))
