# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './docs/funcionario/home_funcionario.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HomeFuncionario(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 650)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 650))
        MainWindow.setMaximumSize(QtCore.QSize(1000, 650))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./docs/funcionario/../../../../../.designer/ES - projeto/img/seguro-de-automovel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-2, -5, 1001, 75))
        self.label.setStyleSheet("background-color: rgb(196, 196, 196);\n"
"color: rgb(75, 74, 74);\n"
"font: 24pt \"Segoe UI\";\n"
"padding: 10px;\n"
"border:none;")
        self.label.setObjectName("label")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(0, 70, 1001, 45))
        self.groupBox.setStyleSheet("background-color: rgb(166, 159, 159);\n"
"padding-inline:10px;\n"
"border:none;")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.btnVagas = QtWidgets.QPushButton(self.groupBox)
        self.btnVagas.setGeometry(QtCore.QRect(130, 0, 61, 41))
        self.btnVagas.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnVagas.setStyleSheet("color: rgb(75, 74, 74);\n"
"font: 14pt \"Segoe UI\";\n"
"text-align: left;")
        self.btnVagas.setObjectName("btnVagas")
        self.btnEstacionamento = QtWidgets.QPushButton(self.groupBox)
        self.btnEstacionamento.setGeometry(QtCore.QRect(200, 0, 161, 41))
        self.btnEstacionamento.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnEstacionamento.setStyleSheet("color: rgb(75, 74, 74);\n"
"font: 14pt \"Segoe UI\";\n"
"text-align: left;")
        self.btnEstacionamento.setObjectName("btnEstacionamento")
        self.btnReservas = QtWidgets.QPushButton(self.groupBox)
        self.btnReservas.setGeometry(QtCore.QRect(450, 0, 91, 41))
        self.btnReservas.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnReservas.setStyleSheet("color: rgb(75, 74, 74);\n"
"font: 14pt \"Segoe UI\";\n"
"text-align: left;")
        self.btnReservas.setObjectName("btnReservas")
        self.btnSair = QtWidgets.QPushButton(self.groupBox)
        self.btnSair.setGeometry(QtCore.QRect(550, 0, 41, 41))
        self.btnSair.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnSair.setStyleSheet("color: rgb(75, 74, 74);\n"
"font: 14pt \"Segoe UI\";\n"
"text-align: left;")
        self.btnSair.setObjectName("btnSair")
        self.btnCadastros = QtWidgets.QPushButton(self.groupBox)
        self.btnCadastros.setGeometry(QtCore.QRect(20, 0, 101, 41))
        self.btnCadastros.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnCadastros.setStyleSheet("color: rgb(75, 74, 74);\n"
"font: 14pt \"Segoe UI\";\n"
"text-align: left;")
        self.btnCadastros.setObjectName("btnCadastros")
        self.btnAlugar = QtWidgets.QPushButton(self.groupBox)
        self.btnAlugar.setGeometry(QtCore.QRect(370, 0, 81, 41))
        self.btnAlugar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnAlugar.setStyleSheet("color: rgb(75, 74, 74);\n"
"font: 14pt \"Segoe UI\";\n"
"text-align: left;")
        self.btnAlugar.setObjectName("btnAlugar")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 620, 1001, 31))
        self.label_2.setStyleSheet("background-color: rgb(196, 196, 196);\n"
"color: rgb(75, 74, 74);\n"
"")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.fundo = QtWidgets.QLabel(self.centralwidget)
        self.fundo.setGeometry(QtCore.QRect(10, 130, 961, 321))
        self.fundo.setText("")
        self.fundo.setPixmap(QtGui.QPixmap("./docs/funcionario/imagens/carro.png"))
        self.fundo.setAlignment(QtCore.Qt.AlignCenter)
        self.fundo.setObjectName("fundo")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sistema de estacionamento - Página Inicial"))
        self.label.setText(_translate("MainWindow", "Sistema de estacionamento"))
        self.btnVagas.setText(_translate("MainWindow", "Vagas"))
        self.btnEstacionamento.setText(_translate("MainWindow", "Estacionamento"))
        self.btnReservas.setText(_translate("MainWindow", "Reservar "))
        self.btnSair.setText(_translate("MainWindow", "Sair"))
        self.btnCadastros.setText(_translate("MainWindow", "Cadastros"))
        self.btnAlugar.setText(_translate("MainWindow", "Alugar"))
        self.label_2.setText(_translate("MainWindow", "Sistema de stacionamento"))
