# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './docs/funcionario/vagas_funcionario.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VagasFuncionario(object):
    def setupUi(self, VagasFuncionario):
        VagasFuncionario.setObjectName("VagasFuncionario")
        VagasFuncionario.resize(1000, 650)
        VagasFuncionario.setMinimumSize(QtCore.QSize(1000, 650))
        VagasFuncionario.setMaximumSize(QtCore.QSize(1000, 650))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./docs/funcionario/imagens/seguro-de-automovel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        VagasFuncionario.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(VagasFuncionario)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(0, 70, 1001, 45))
        self.groupBox.setStyleSheet("background-color: rgb(166, 159, 159);\n"
"padding-inline:10px;\n"
"border:none;")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.btnSair = QtWidgets.QPushButton(self.groupBox)
        self.btnSair.setGeometry(QtCore.QRect(370, 0, 41, 41))
        self.btnSair.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnSair.setStyleSheet("color: rgb(75, 74, 74);\n"
"font: 14pt \"Segoe UI\";\n"
"text-align: left;")
        self.btnSair.setObjectName("btnSair")
        self.btnCadastros = QtWidgets.QPushButton(self.groupBox)
        self.btnCadastros.setGeometry(QtCore.QRect(90, 0, 101, 41))
        self.btnCadastros.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnCadastros.setStyleSheet("color: rgb(75, 74, 74);\n"
"font: 14pt \"Segoe UI\";\n"
"text-align: left;")
        self.btnCadastros.setObjectName("btnCadastros")
        self.btnEstacionamento = QtWidgets.QPushButton(self.groupBox)
        self.btnEstacionamento.setGeometry(QtCore.QRect(200, 0, 161, 41))
        self.btnEstacionamento.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnEstacionamento.setStyleSheet("color: rgb(75, 74, 74);\n"
"font: 14pt \"Segoe UI\";\n"
"text-align: left;")
        self.btnEstacionamento.setObjectName("btnEstacionamento")
        self.btnHome = QtWidgets.QPushButton(self.groupBox)
        self.btnHome.setGeometry(QtCore.QRect(20, 0, 61, 41))
        self.btnHome.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnHome.setStyleSheet("color: rgb(75, 74, 74);\n"
"font: 14pt \"Segoe UI\";\n"
"text-align: left;\n"
"")
        self.btnHome.setObjectName("btnHome")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, -5, 1001, 75))
        self.label.setStyleSheet("background-color: rgb(196, 196, 196);\n"
"color: rgb(75, 74, 74);\n"
"font: 24pt \"Segoe UI\";\n"
"padding: 10px;\n"
"border:none;")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 620, 1001, 31))
        self.label_2.setStyleSheet("background-color: rgb(196, 196, 196);\n"
"color: rgb(75, 74, 74);\n"
"")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 130, 151, 31))
        self.label_3.setStyleSheet("color: rgb(75, 74, 74);\n"
"font: 14pt \"Segoe UI\";")
        self.label_3.setObjectName("label_3")
        self.tableVagas = QtWidgets.QTableWidget(self.centralwidget)
        self.tableVagas.setGeometry(QtCore.QRect(20, 170, 961, 351))
        self.tableVagas.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.tableVagas.setAutoFillBackground(True)
        self.tableVagas.setStyleSheet("color: rgb(75, 74, 74);")
        self.tableVagas.setInputMethodHints(QtCore.Qt.ImhNone)
        self.tableVagas.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableVagas.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableVagas.setAlternatingRowColors(True)
        self.tableVagas.setShowGrid(False)
        self.tableVagas.setGridStyle(QtCore.Qt.NoPen)
        self.tableVagas.setWordWrap(True)
        self.tableVagas.setObjectName("tableVagas")
        self.tableVagas.setColumnCount(4)
        self.tableVagas.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tableVagas.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tableVagas.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tableVagas.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tableVagas.setHorizontalHeaderItem(3, item)
        self.tableVagas.horizontalHeader().setCascadingSectionResizes(False)
        self.tableVagas.horizontalHeader().setDefaultSectionSize(240)
        self.btnAlugar = QtWidgets.QPushButton(self.centralwidget)
        self.btnAlugar.setGeometry(QtCore.QRect(770, 540, 100, 35))
        self.btnAlugar.setMinimumSize(QtCore.QSize(100, 35))
        self.btnAlugar.setMaximumSize(QtCore.QSize(100, 35))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btnAlugar.setFont(font)
        self.btnAlugar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnAlugar.setStyleSheet("background-color: rgb(53, 119, 218);\n"
"color: rgb(255, 255, 255);\n"
"border: none;\n"
"border-radius:10px;")
        self.btnAlugar.setObjectName("btnAlugar")
        self.btnReservar = QtWidgets.QPushButton(self.centralwidget)
        self.btnReservar.setGeometry(QtCore.QRect(880, 540, 100, 35))
        self.btnReservar.setMinimumSize(QtCore.QSize(100, 35))
        self.btnReservar.setMaximumSize(QtCore.QSize(100, 35))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btnReservar.setFont(font)
        self.btnReservar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnReservar.setStyleSheet("border: none;\n"
"border-radius:10px;\n"
"background-color: rgb(53, 119, 218);\n"
"color: rgb(255, 255, 255);")
        self.btnReservar.setObjectName("btnReservar")
        self.btnMudarStatus = QtWidgets.QPushButton(self.centralwidget)
        self.btnMudarStatus.setGeometry(QtCore.QRect(649, 540, 111, 35))
        self.btnMudarStatus.setMinimumSize(QtCore.QSize(100, 35))
        self.btnMudarStatus.setMaximumSize(QtCore.QSize(150, 35))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btnMudarStatus.setFont(font)
        self.btnMudarStatus.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnMudarStatus.setStyleSheet("background-color: rgb(53, 119, 218);\n"
"color: rgb(255, 255, 255);\n"
"border: none;\n"
"border-radius:10px;")
        self.btnMudarStatus.setObjectName("btnMudarStatus")
        VagasFuncionario.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(VagasFuncionario)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 22))
        self.menubar.setObjectName("menubar")
        VagasFuncionario.setMenuBar(self.menubar)

        self.retranslateUi(VagasFuncionario)
        QtCore.QMetaObject.connectSlotsByName(VagasFuncionario)

    def retranslateUi(self, VagasFuncionario):
        _translate = QtCore.QCoreApplication.translate
        VagasFuncionario.setWindowTitle(_translate("VagasFuncionario", "Sistema de estacionamento - Vagas"))
        self.btnSair.setText(_translate("VagasFuncionario", "Sair"))
        self.btnCadastros.setText(_translate("VagasFuncionario", "Cadastros"))
        self.btnEstacionamento.setText(_translate("VagasFuncionario", "Estacionamento"))
        self.btnHome.setText(_translate("VagasFuncionario", "Home"))
        self.label.setText(_translate("VagasFuncionario", "Sistema de estacionamento"))
        self.label_2.setText(_translate("VagasFuncionario", "Sistema de stacionamento"))
        self.label_3.setText(_translate("VagasFuncionario", "Vagas"))
        item = self.tableVagas.horizontalHeaderItem(0)
        item.setText(_translate("VagasFuncionario", "Número da vaga"))
        item = self.tableVagas.horizontalHeaderItem(1)
        item.setText(_translate("VagasFuncionario", "Status"))
        item = self.tableVagas.horizontalHeaderItem(2)
        item.setText(_translate("VagasFuncionario", "Aluguel"))
        item = self.tableVagas.horizontalHeaderItem(3)
        item.setText(_translate("VagasFuncionario", "Tempo"))
        self.btnAlugar.setText(_translate("VagasFuncionario", "Alugar"))
        self.btnReservar.setText(_translate("VagasFuncionario", "Reservar"))
        self.btnMudarStatus.setText(_translate("VagasFuncionario", "Mudar Status"))
