# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './docs/cliente/estacionamento_cliente.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EstacionamentoCliente(object):
    def setupUi(self, EstacionamentoCliente):
        EstacionamentoCliente.setObjectName("EstacionamentoCliente")
        EstacionamentoCliente.resize(1000, 650)
        EstacionamentoCliente.setMinimumSize(QtCore.QSize(1000, 650))
        EstacionamentoCliente.setMaximumSize(QtCore.QSize(1000, 650))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./docs/cliente/imagens/seguro-de-automovel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        EstacionamentoCliente.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(EstacionamentoCliente)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(0, 70, 1001, 45))
        self.groupBox.setStyleSheet("background-color: rgb(166, 159, 159);\n"
"padding-inline:10px;\n"
"border:none;")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.btnHome = QtWidgets.QPushButton(self.groupBox)
        self.btnHome.setGeometry(QtCore.QRect(20, 0, 75, 41))
        self.btnHome.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnHome.setStyleSheet("color: rgb(75, 74, 74);\n"
"font: 14pt \"Segoe UI\";\n"
"text-align: left;")
        self.btnHome.setObjectName("btnHome")
        self.btnVagas = QtWidgets.QPushButton(self.groupBox)
        self.btnVagas.setGeometry(QtCore.QRect(90, 0, 61, 41))
        self.btnVagas.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnVagas.setStyleSheet("color: rgb(75, 74, 74);\n"
"font: 14pt \"Segoe UI\";\n"
"text-align: left;")
        self.btnVagas.setObjectName("btnVagas")
        self.btnMinhaReserva = QtWidgets.QPushButton(self.groupBox)
        self.btnMinhaReserva.setGeometry(QtCore.QRect(160, 0, 151, 41))
        self.btnMinhaReserva.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnMinhaReserva.setStyleSheet("color: rgb(75, 74, 74);\n"
"font: 14pt \"Segoe UI\";\n"
"text-align: left;")
        self.btnMinhaReserva.setObjectName("btnMinhaReserva")
        self.btnSair = QtWidgets.QPushButton(self.groupBox)
        self.btnSair.setGeometry(QtCore.QRect(310, 0, 41, 41))
        self.btnSair.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnSair.setStyleSheet("color: rgb(75, 74, 74);\n"
"font: 14pt \"Segoe UI\";\n"
"text-align: left;")
        self.btnSair.setObjectName("btnSair")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, -5, 1001, 75))
        self.label.setStyleSheet("background-color: rgb(196, 196, 196);\n"
"color: rgb(75, 74, 74);\n"
"font: 24pt \"Segoe UI\";\n"
"padding: 10px;\n"
"border:none;")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 620, 1001, 31))
        self.label_2.setStyleSheet("background-color: rgb(196, 196, 196);\n"
"color: rgb(75, 74, 74);\n"
"")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 130, 161, 31))
        self.label_3.setStyleSheet("color: rgb(75, 74, 74);\n"
"font: 14pt \"Segoe UI\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(50, 170, 911, 381))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("./docs/cliente/imagens/mapiamento.png"))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.vaga1 = QtWidgets.QLabel(self.centralwidget)
        self.vaga1.setGeometry(QtCore.QRect(120, 160, 31, 31))
        self.vaga1.setStyleSheet("border-radius:15px;")
        self.vaga1.setText("")
        self.vaga1.setObjectName("vaga1")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(190, 160, 31, 31))
        self.label_6.setStyleSheet("\n"
"border-radius:15px;")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(410, 160, 31, 31))
        self.label_7.setStyleSheet("\n"
"border-radius:15px;")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(340, 160, 31, 31))
        self.label_8.setStyleSheet("\n"
"border-radius:15px;")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(230, 180, 31, 31))
        self.label_9.setStyleSheet("\n"
"border-radius:15px;")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(680, 160, 31, 31))
        self.label_10.setStyleSheet("\n"
"border-radius:15px;")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(610, 160, 31, 31))
        self.label_11.setStyleSheet("\n"
"border-radius:15px;")
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(550, 160, 31, 31))
        self.label_12.setStyleSheet("\n"
"border-radius:15px;")
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(480, 160, 31, 31))
        self.label_13.setStyleSheet("\n"
"border-radius:15px;")
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(750, 160, 31, 31))
        self.label_14.setStyleSheet("\n"
"border-radius:15px;")
        self.label_14.setText("")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(610, 480, 31, 31))
        self.label_15.setStyleSheet("\n"
"border-radius:15px;")
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(340, 480, 31, 31))
        self.label_16.setStyleSheet("\n"
"border-radius:15px;")
        self.label_16.setText("")
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(680, 480, 31, 31))
        self.label_17.setStyleSheet("\n"
"border-radius:15px;")
        self.label_17.setText("")
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(550, 480, 31, 31))
        self.label_18.setStyleSheet("\n"
"border-radius:15px;")
        self.label_18.setText("")
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(120, 480, 31, 31))
        self.label_19.setStyleSheet("\n"
"border-radius:15px;")
        self.label_19.setText("")
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(410, 480, 31, 31))
        self.label_20.setStyleSheet("\n"
"border-radius:15px;")
        self.label_20.setText("")
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(750, 480, 31, 31))
        self.label_21.setStyleSheet("\n"
"border-radius:15px;")
        self.label_21.setText("")
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(190, 480, 31, 31))
        self.label_22.setStyleSheet("\n"
"border-radius:15px;")
        self.label_22.setText("")
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(270, 480, 31, 31))
        self.label_23.setStyleSheet("\n"
"border-radius:15px;")
        self.label_23.setText("")
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(480, 480, 31, 31))
        self.label_24.setStyleSheet("\n"
"border-radius:15px;")
        self.label_24.setText("")
        self.label_24.setObjectName("label_24")
        self.btnReservar = QtWidgets.QPushButton(self.centralwidget)
        self.btnReservar.setGeometry(QtCore.QRect(820, 570, 111, 35))
        self.btnReservar.setMinimumSize(QtCore.QSize(100, 35))
        self.btnReservar.setMaximumSize(QtCore.QSize(150, 35))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btnReservar.setFont(font)
        self.btnReservar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnReservar.setStyleSheet("background-color: rgb(53, 119, 218);\n"
"color: rgb(255, 255, 255);\n"
"border: none;\n"
"border-radius:10px;")
        self.btnReservar.setObjectName("btnReservar")
        self.btnAlugar = QtWidgets.QPushButton(self.centralwidget)
        self.btnAlugar.setGeometry(QtCore.QRect(710, 570, 100, 35))
        self.btnAlugar.setMinimumSize(QtCore.QSize(100, 35))
        self.btnAlugar.setMaximumSize(QtCore.QSize(100, 35))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btnAlugar.setFont(font)
        self.btnAlugar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnAlugar.setStyleSheet("background-color: rgb(53, 119, 218);\n"
"color: rgb(255, 255, 255);\n"
"border: none;\n"
"border-radius:10px;")
        self.btnAlugar.setObjectName("btnAlugar")
        EstacionamentoCliente.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(EstacionamentoCliente)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 22))
        self.menubar.setObjectName("menubar")
        EstacionamentoCliente.setMenuBar(self.menubar)

        self.retranslateUi(EstacionamentoCliente)
        QtCore.QMetaObject.connectSlotsByName(EstacionamentoCliente)

    def retranslateUi(self, EstacionamentoCliente):
        _translate = QtCore.QCoreApplication.translate
        EstacionamentoCliente.setWindowTitle(_translate("EstacionamentoCliente", "Sistema de estacionamento - Estacionamento"))
        self.btnHome.setText(_translate("EstacionamentoCliente", "Home"))
        self.btnVagas.setText(_translate("EstacionamentoCliente", "Vagas"))
        self.btnMinhaReserva.setText(_translate("EstacionamentoCliente", "Minha Reserva"))
        self.btnSair.setText(_translate("EstacionamentoCliente", "Sair"))
        self.label.setText(_translate("EstacionamentoCliente", "Sistema de estacionamento"))
        self.label_2.setText(_translate("EstacionamentoCliente", "Sistema de stacionamento"))
        self.label_3.setText(_translate("EstacionamentoCliente", "Estacionamento"))
        self.btnReservar.setText(_translate("EstacionamentoCliente", "Reservar"))
        self.btnAlugar.setText(_translate("EstacionamentoCliente", "Alugar"))
