# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './docs/cliente/reservas_cliente.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ReservasCliente(object):
    def setupUi(self, ReservasCliente):
        ReservasCliente.setObjectName("ReservasCliente")
        ReservasCliente.resize(1000, 650)
        ReservasCliente.setMinimumSize(QtCore.QSize(1000, 650))
        ReservasCliente.setMaximumSize(QtCore.QSize(1000, 650))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./docs/cliente/imagens/seguro-de-automovel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ReservasCliente.setWindowIcon(icon)
        ReservasCliente.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(ReservasCliente)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(0, 70, 1001, 45))
        self.groupBox.setStyleSheet("background-color: rgb(166, 159, 159);\n"
"padding-inline:10px;\n"
"border:none;")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.btnHome = QtWidgets.QPushButton(self.groupBox)
        self.btnHome.setGeometry(QtCore.QRect(20, 0, 81, 41))
        self.btnHome.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnHome.setStyleSheet("color: rgb(75, 74, 74);\n"
"font: 14pt \"Segoe UI\";\n"
"text-align: left;\n"
"padding-right:25px;")
        self.btnHome.setObjectName("btnHome")
        self.btnEstacionamento = QtWidgets.QPushButton(self.groupBox)
        self.btnEstacionamento.setGeometry(QtCore.QRect(160, 0, 181, 41))
        self.btnEstacionamento.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnEstacionamento.setStyleSheet("color: rgb(75, 74, 74);\n"
"font: 14pt \"Segoe UI\";\n"
"text-align: left;\n"
"padding-right:25px;")
        self.btnEstacionamento.setObjectName("btnEstacionamento")
        self.btnSair = QtWidgets.QPushButton(self.groupBox)
        self.btnSair.setGeometry(QtCore.QRect(330, 0, 41, 41))
        self.btnSair.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnSair.setStyleSheet("color: rgb(75, 74, 74);\n"
"font: 14pt \"Segoe UI\";\n"
"text-align: left;")
        self.btnSair.setObjectName("btnSair")
        self.btnVagas = QtWidgets.QPushButton(self.groupBox)
        self.btnVagas.setGeometry(QtCore.QRect(90, 0, 61, 41))
        self.btnVagas.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnVagas.setStyleSheet("color: rgb(75, 74, 74);\n"
"font: 14pt \"Segoe UI\";\n"
"text-align: left;")
        self.btnVagas.setObjectName("btnVagas")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, -5, 1001, 75))
        self.label.setStyleSheet("background-color: rgb(196, 196, 196);\n"
"color: rgb(75, 74, 74);\n"
"font: 24pt \"Segoe UI\";\n"
"padding: 10px;\n"
"border:none;")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 620, 1001, 31))
        self.label_2.setStyleSheet("background-color: rgb(196, 196, 196);\n"
"color: rgb(75, 74, 74);\n"
"")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 130, 151, 31))
        self.label_3.setStyleSheet("color: rgb(75, 74, 74);\n"
"font: 14pt \"Segoe UI\";")
        self.label_3.setObjectName("label_3")
        self.tableReservaCliente = QtWidgets.QTableWidget(self.centralwidget)
        self.tableReservaCliente.setGeometry(QtCore.QRect(20, 170, 961, 91))
        self.tableReservaCliente.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.tableReservaCliente.setAutoFillBackground(True)
        self.tableReservaCliente.setStyleSheet("color: rgb(75, 74, 74);\n"
"gridline-color: rgb(222, 222, 222);\n"
"alternate-background-color: rgb(255, 255, 255);")
        self.tableReservaCliente.setInputMethodHints(QtCore.Qt.ImhNone)
        self.tableReservaCliente.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableReservaCliente.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableReservaCliente.setAlternatingRowColors(True)
        self.tableReservaCliente.setShowGrid(False)
        self.tableReservaCliente.setGridStyle(QtCore.Qt.NoPen)
        self.tableReservaCliente.setWordWrap(True)
        self.tableReservaCliente.setObjectName("tableReservaCliente")
        self.tableReservaCliente.setColumnCount(4)
        self.tableReservaCliente.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tableReservaCliente.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tableReservaCliente.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tableReservaCliente.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tableReservaCliente.setHorizontalHeaderItem(3, item)
        self.tableReservaCliente.horizontalHeader().setCascadingSectionResizes(False)
        self.tableReservaCliente.horizontalHeader().setDefaultSectionSize(240)
        self.btnAtualizarReserva = QtWidgets.QPushButton(self.centralwidget)
        self.btnAtualizarReserva.setGeometry(QtCore.QRect(860, 550, 121, 35))
        self.btnAtualizarReserva.setMinimumSize(QtCore.QSize(100, 35))
        self.btnAtualizarReserva.setMaximumSize(QtCore.QSize(150, 50))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btnAtualizarReserva.setFont(font)
        self.btnAtualizarReserva.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnAtualizarReserva.setStyleSheet("border: none;\n"
"border-radius:10px;\n"
"background-color: rgb(53, 119, 218);\n"
"color: rgb(255, 255, 255);")
        self.btnAtualizarReserva.setObjectName("btnAtualizarReserva")
        self.btnCancelar = QtWidgets.QPushButton(self.centralwidget)
        self.btnCancelar.setEnabled(False)
        self.btnCancelar.setGeometry(QtCore.QRect(730, 550, 121, 35))
        self.btnCancelar.setMinimumSize(QtCore.QSize(100, 35))
        self.btnCancelar.setMaximumSize(QtCore.QSize(200, 35))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btnCancelar.setFont(font)
        self.btnCancelar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnCancelar.setStyleSheet("background: #FF0505;\n"
"color: rgb(255, 255, 255);\n"
"border: none;\n"
"border-radius:10px;")
        self.btnCancelar.setObjectName("btnCancelar")
        ReservasCliente.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ReservasCliente)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 22))
        self.menubar.setObjectName("menubar")
        ReservasCliente.setMenuBar(self.menubar)

        self.retranslateUi(ReservasCliente)
        QtCore.QMetaObject.connectSlotsByName(ReservasCliente)

    def retranslateUi(self, ReservasCliente):
        _translate = QtCore.QCoreApplication.translate
        ReservasCliente.setWindowTitle(_translate("ReservasCliente", "Sistema de estacionamento - Reservas"))
        self.btnHome.setText(_translate("ReservasCliente", "Home"))
        self.btnEstacionamento.setText(_translate("ReservasCliente", "Estacionamento"))
        self.btnSair.setText(_translate("ReservasCliente", "Sair"))
        self.btnVagas.setText(_translate("ReservasCliente", "Vagas"))
        self.label.setText(_translate("ReservasCliente", "Sistema de estacionamento"))
        self.label_2.setText(_translate("ReservasCliente", "Sistema de stacionamento"))
        self.label_3.setText(_translate("ReservasCliente", "Minha reserva"))
        item = self.tableReservaCliente.horizontalHeaderItem(0)
        item.setText(_translate("ReservasCliente", "Número da vaga"))
        item = self.tableReservaCliente.horizontalHeaderItem(1)
        item.setText(_translate("ReservasCliente", "Data"))
        item = self.tableReservaCliente.horizontalHeaderItem(2)
        item.setText(_translate("ReservasCliente", "Intervalo"))
        item = self.tableReservaCliente.horizontalHeaderItem(3)
        item.setText(_translate("ReservasCliente", "Aluguel"))
        self.btnAtualizarReserva.setText(_translate("ReservasCliente", "Atualizar"))
        self.btnCancelar.setText(_translate("ReservasCliente", "Cancelar reserva"))
