# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './docs/cliente/vagas_cliente.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VagasCliente(object):
    def setupUi(self, VagasCliente):
        VagasCliente.setObjectName("VagasCliente")
        VagasCliente.resize(1000, 650)
        VagasCliente.setMinimumSize(QtCore.QSize(1000, 650))
        VagasCliente.setMaximumSize(QtCore.QSize(1000, 650))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./docs/cliente/imagens/seguro-de-automovel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        VagasCliente.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(VagasCliente)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(0, 70, 1001, 45))
        self.groupBox.setStyleSheet("background-color: rgb(166, 159, 159);\n"
"padding-inline:10px;\n"
"border:none;")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.btnHome = QtWidgets.QPushButton(self.groupBox)
        self.btnHome.setGeometry(QtCore.QRect(20, 0, 81, 41))
        self.btnHome.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnHome.setStyleSheet("color: rgb(75, 74, 74);\n"
"font: 14pt \"Segoe UI\";\n"
"text-align: left;\n"
"padding-right:25px;")
        self.btnHome.setObjectName("btnHome")
        self.btnEstacionamento = QtWidgets.QPushButton(self.groupBox)
        self.btnEstacionamento.setGeometry(QtCore.QRect(90, 0, 156, 41))
        self.btnEstacionamento.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnEstacionamento.setStyleSheet("color: rgb(75, 74, 74);\n"
"font: 14pt \"Segoe UI\";\n"
"text-align: left;")
        self.btnEstacionamento.setObjectName("btnEstacionamento")
        self.btnReservas = QtWidgets.QPushButton(self.groupBox)
        self.btnReservas.setGeometry(QtCore.QRect(250, 0, 166, 41))
        self.btnReservas.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnReservas.setStyleSheet("color: rgb(75, 74, 74);\n"
"font: 14pt \"Segoe UI\";\n"
"text-align: left;")
        self.btnReservas.setObjectName("btnReservas")
        self.btnSair = QtWidgets.QPushButton(self.groupBox)
        self.btnSair.setGeometry(QtCore.QRect(400, 0, 75, 41))
        self.btnSair.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnSair.setStyleSheet("color: rgb(75, 74, 74);\n"
"font: 14pt \"Segoe UI\";\n"
"text-align: left;")
        self.btnSair.setObjectName("btnSair")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, -5, 1001, 75))
        self.label.setStyleSheet("background-color: rgb(196, 196, 196);\n"
"color: rgb(75, 74, 74);\n"
"font: 24pt \"Segoe UI\";\n"
"padding: 10px;\n"
"border:none;")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 620, 1001, 31))
        self.label_2.setStyleSheet("background-color: rgb(196, 196, 196);\n"
"color: rgb(75, 74, 74);\n"
"")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 130, 151, 31))
        self.label_3.setStyleSheet("color: rgb(75, 74, 74);\n"
"font: 14pt \"Segoe UI\";")
        self.label_3.setObjectName("label_3")
        self.tableVagas = QtWidgets.QTableWidget(self.centralwidget)
        self.tableVagas.setGeometry(QtCore.QRect(20, 170, 861, 365))
        self.tableVagas.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.tableVagas.setAutoFillBackground(True)
        self.tableVagas.setStyleSheet("color: rgb(75, 74, 74);")
        self.tableVagas.setInputMethodHints(QtCore.Qt.ImhNone)
        self.tableVagas.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableVagas.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableVagas.setAlternatingRowColors(True)
        self.tableVagas.setShowGrid(False)
        self.tableVagas.setGridStyle(QtCore.Qt.NoPen)
        self.tableVagas.setWordWrap(True)
        self.tableVagas.setObjectName("tableVagas")
        self.tableVagas.setColumnCount(4)
        self.tableVagas.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tableVagas.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tableVagas.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tableVagas.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tableVagas.setHorizontalHeaderItem(3, item)
        self.tableVagas.horizontalHeader().setCascadingSectionResizes(False)
        self.tableVagas.horizontalHeader().setDefaultSectionSize(215)
        self.btnAlugar = QtWidgets.QPushButton(self.centralwidget)
        self.btnAlugar.setGeometry(QtCore.QRect(770, 560, 100, 35))
        self.btnAlugar.setMinimumSize(QtCore.QSize(100, 35))
        self.btnAlugar.setMaximumSize(QtCore.QSize(100, 35))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btnAlugar.setFont(font)
        self.btnAlugar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnAlugar.setStyleSheet("background-color: rgb(53, 119, 218);\n"
"color: rgb(255, 255, 255);\n"
"border: none;\n"
"border-radius:10px;")
        self.btnAlugar.setObjectName("btnAlugar")
        self.btnReservar = QtWidgets.QPushButton(self.centralwidget)
        self.btnReservar.setGeometry(QtCore.QRect(880, 560, 100, 35))
        self.btnReservar.setMinimumSize(QtCore.QSize(100, 35))
        self.btnReservar.setMaximumSize(QtCore.QSize(100, 35))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btnReservar.setFont(font)
        self.btnReservar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnReservar.setStyleSheet("border: none;\n"
"border-radius:10px;\n"
"background-color: rgb(53, 119, 218);\n"
"color: rgb(255, 255, 255);")
        self.btnReservar.setObjectName("btnReservar")
        VagasCliente.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(VagasCliente)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 22))
        self.menubar.setObjectName("menubar")
        VagasCliente.setMenuBar(self.menubar)

        self.retranslateUi(VagasCliente)
        QtCore.QMetaObject.connectSlotsByName(VagasCliente)

    def retranslateUi(self, VagasCliente):
        _translate = QtCore.QCoreApplication.translate
        VagasCliente.setWindowTitle(_translate("VagasCliente", "Sistema de estacionamento - Vagas"))
        self.btnHome.setText(_translate("VagasCliente", "Home"))
        self.btnEstacionamento.setText(_translate("VagasCliente", "Estacionamento"))
        self.btnReservas.setText(_translate("VagasCliente", "Minha Reserva "))
        self.btnSair.setText(_translate("VagasCliente", "Sair"))
        self.label.setText(_translate("VagasCliente", "Sistema de estacionamento"))
        self.label_2.setText(_translate("VagasCliente", "Sistema de stacionamento"))
        self.label_3.setText(_translate("VagasCliente", "Vagas"))
        item = self.tableVagas.horizontalHeaderItem(0)
        item.setText(_translate("VagasCliente", "Número da vaga"))
        item = self.tableVagas.horizontalHeaderItem(1)
        item.setText(_translate("VagasCliente", "Status"))
        item = self.tableVagas.horizontalHeaderItem(2)
        item.setText(_translate("VagasCliente", "Aluguel"))
        item = self.tableVagas.horizontalHeaderItem(3)
        item.setText(_translate("VagasCliente", "Tempo"))
        self.btnAlugar.setText(_translate("VagasCliente", "Alugar"))
        self.btnReservar.setText(_translate("VagasCliente", "Reservar"))
