# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './docs/cliente/cadastro.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CadastrarCliente(object):
    def setupUi(self, CadastrarFuncionario):
        CadastrarFuncionario.setObjectName("CadastrarFuncionario")
        CadastrarFuncionario.resize(1000, 650)
        CadastrarFuncionario.setMinimumSize(QtCore.QSize(1000, 650))
        CadastrarFuncionario.setMaximumSize(QtCore.QSize(1000, 650))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./docs/cliente/imagens/seguro-de-automovel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        CadastrarFuncionario.setWindowIcon(icon)
        CadastrarFuncionario.setStyleSheet("background-color: rgb(229, 229, 229);")
        self.centralwidget = QtWidgets.QWidget(CadastrarFuncionario)
        self.centralwidget.setObjectName("centralwidget")
        self.btnCadastrar = QtWidgets.QPushButton(self.centralwidget)
        self.btnCadastrar.setGeometry(QtCore.QRect(340, 320, 321, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnCadastrar.setFont(font)
        self.btnCadastrar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnCadastrar.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(53, 119, 218);\n"
"border: none;\n"
"border-radius:10px;")
        self.btnCadastrar.setObjectName("btnCadastrar")
        self.nome_usuario = QtWidgets.QLineEdit(self.centralwidget)
        self.nome_usuario.setGeometry(QtCore.QRect(340, 210, 321, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.nome_usuario.setFont(font)
        self.nome_usuario.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 11pt \"Segoe UI\";\n"
"padding-left: 40px;\n"
"border-radius:10px;\n"
"color: rgb(75, 74, 74);")
        self.nome_usuario.setText("")
        self.nome_usuario.setObjectName("nome_usuario")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 130, 1001, 41))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(75, 74, 74);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.senha = QtWidgets.QLineEdit(self.centralwidget)
        self.senha.setEnabled(True)
        self.senha.setGeometry(QtCore.QRect(340, 260, 321, 41))
        self.senha.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 11pt \"Segoe UI\";\n"
"padding-left: 40px;\n"
"border-radius:10px;\n"
"color: rgb(75, 74, 74);")
        self.senha.setEchoMode(QtWidgets.QLineEdit.Password)
        self.senha.setObjectName("senha")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(360, 260, 21, 41))
        self.label_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("./docs/cliente/imagens/cadeado16.png"))
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(360, 210, 21, 41))
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("./docs/cliente/imagens/user16.png"))
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(0, 80, 1001, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(75, 74, 74);")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        CadastrarFuncionario.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(CadastrarFuncionario)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 22))
        self.menubar.setObjectName("menubar")
        CadastrarFuncionario.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(CadastrarFuncionario)
        self.statusbar.setObjectName("statusbar")
        CadastrarFuncionario.setStatusBar(self.statusbar)

        self.retranslateUi(CadastrarFuncionario)
        QtCore.QMetaObject.connectSlotsByName(CadastrarFuncionario)

    def retranslateUi(self, CadastrarFuncionario):
        _translate = QtCore.QCoreApplication.translate
        CadastrarFuncionario.setWindowTitle(_translate("CadastrarFuncionario", "Sistema de estacionamento - Cadastre-se"))
        self.btnCadastrar.setText(_translate("CadastrarFuncionario", "Cadastrar"))
        self.nome_usuario.setPlaceholderText(_translate("CadastrarFuncionario", "Nome de usuário"))
        self.label.setText(_translate("CadastrarFuncionario", "Criar login"))
        self.senha.setPlaceholderText(_translate("CadastrarFuncionario", "Senha "))
        self.label_4.setText(_translate("CadastrarFuncionario", "Sistema de estacionamento"))
