# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './docs/confirmacao_pagamento.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ConfirmacaoPagamento(object):
    def setupUi(self, ConfirmarPagamento):
        ConfirmarPagamento.setObjectName("ConfirmacaoPagamento")
        ConfirmarPagamento.resize(300, 300)
        ConfirmarPagamento.setMinimumSize(QtCore.QSize(300, 300))
        ConfirmarPagamento.setMaximumSize(QtCore.QSize(300, 550))
        ConfirmarPagamento.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./docs/imagens/seguro-de-automovel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ConfirmarPagamento.setWindowIcon(icon)
        ConfirmarPagamento.setStyleSheet("background-color: rgb(242, 237, 237);")
        self.centralwidget = QtWidgets.QWidget(ConfirmarPagamento)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 300, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(196, 196, 196);\n"
"color: rgb(75, 74, 74);\n"
"\n"
"padding: 10px;\n"
"border:none;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.btnCancelar = QtWidgets.QPushButton(self.centralwidget)
        self.btnCancelar.setGeometry(QtCore.QRect(90, 160, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnCancelar.setFont(font)
        self.btnCancelar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnCancelar.setStyleSheet("border: none;\n"
"border-radius:10px;\n"
"background-color:#FF0505;\n"
"color: rgb(255, 255, 255);")
        self.btnCancelar.setObjectName("btnCancelar")
        self.btnConfirmar = QtWidgets.QPushButton(self.centralwidget)
        self.btnConfirmar.setGeometry(QtCore.QRect(90, 110, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnConfirmar.setFont(font)
        self.btnConfirmar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnConfirmar.setStyleSheet("border: none;\n"
"border-radius:10px;\n"
"background-color: #12CF02;\n"
"color: rgb(255, 255, 255);")
        self.btnConfirmar.setObjectName("btnConfirmar")
        ConfirmarPagamento.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ConfirmarPagamento)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 300, 22))
        self.menubar.setObjectName("menubar")
        ConfirmarPagamento.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ConfirmarPagamento)
        self.statusbar.setObjectName("statusbar")
        ConfirmarPagamento.setStatusBar(self.statusbar)

        self.retranslateUi(ConfirmarPagamento)
        QtCore.QMetaObject.connectSlotsByName(ConfirmarPagamento)

    def retranslateUi(self, ConfirmarPagamento):
        _translate = QtCore.QCoreApplication.translate
        ConfirmarPagamento.setWindowTitle(_translate("ConfirmacaoPagamento", "Sistema de estacionamento - Confirmar pagamento"))
        self.label.setText(_translate("ConfirmacaoPagamento", "Confirmar pagamento?"))
        self.btnCancelar.setText(_translate("ConfirmacaoPagamento", "Cancelar"))
        self.btnConfirmar.setText(_translate("ConfirmacaoPagamento", "Confirmar"))
