# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './docs/confirmar_reserva.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ConfirmarReserva(object):
    def setupUi(self, ConfirmarReserva):
        ConfirmarReserva.setObjectName("ConfirmarReserva")
        ConfirmarReserva.resize(300, 300)
        ConfirmarReserva.setMinimumSize(QtCore.QSize(300, 300))
        ConfirmarReserva.setMaximumSize(QtCore.QSize(300, 550))
        ConfirmarReserva.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./docs/imagens/seguro-de-automovel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ConfirmarReserva.setWindowIcon(icon)
        ConfirmarReserva.setStyleSheet("background-color: rgb(242, 237, 237);")
        self.centralwidget = QtWidgets.QWidget(ConfirmarReserva)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 300, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(196, 196, 196);\n"
"color: rgb(75, 74, 74);\n"
"\n"
"padding: 10px;\n"
"border:none;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(60, 90, 181, 121))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(75, 74, 74);\n"
"")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.btnFechar = QtWidgets.QPushButton(self.centralwidget)
        self.btnFechar.setGeometry(QtCore.QRect(110, 220, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnFechar.setFont(font)
        self.btnFechar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnFechar.setStyleSheet("border: none;\n"
"border-radius:10px;\n"
"background-color: rgb(53, 119, 218);\n"
"color: rgb(255, 255, 255);")
        self.btnFechar.setObjectName("btnFechar")
        ConfirmarReserva.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ConfirmarReserva)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 300, 22))
        self.menubar.setObjectName("menubar")
        ConfirmarReserva.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ConfirmarReserva)
        self.statusbar.setObjectName("statusbar")
        ConfirmarReserva.setStatusBar(self.statusbar)

        self.retranslateUi(ConfirmarReserva)
        QtCore.QMetaObject.connectSlotsByName(ConfirmarReserva)

    def retranslateUi(self, ConfirmarReserva):
        _translate = QtCore.QCoreApplication.translate
        ConfirmarReserva.setWindowTitle(_translate("ConfirmarReserva", "Sistema de estacionamento - Confirmação da reserva"))
        self.label.setText(_translate("ConfirmarReserva", "Reserva confirmada!"))
        self.label_2.setText(_translate("ConfirmarReserva", "A Reserva foi\n"
" realizada com\n"
" sucesso!"))
        self.btnFechar.setText(_translate("ConfirmarReserva", "Fechar"))
