# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './docs/confirmar_pagamento.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ConfirmarPagamento(object):
    def setupUi(self, ConfirmarPagamento):
        ConfirmarPagamento.setObjectName("ConfirmarPagamento")
        ConfirmarPagamento.resize(300, 300)
        ConfirmarPagamento.setMinimumSize(QtCore.QSize(300, 300))
        ConfirmarPagamento.setMaximumSize(QtCore.QSize(300, 550))
        ConfirmarPagamento.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./docs/imagens/seguro-de-automovel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ConfirmarPagamento.setWindowIcon(icon)
        ConfirmarPagamento.setStyleSheet("background-color: rgb(242, 237, 237);")
        self.centralwidget = QtWidgets.QWidget(ConfirmarPagamento)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-1, 0, 301, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(196, 196, 196);\n"
"color: rgb(75, 74, 74);\n"
"\n"
"padding: 10px;\n"
"border:none;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(60, 90, 181, 121))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(75, 74, 74);\n"
"")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.btnFechar = QtWidgets.QPushButton(self.centralwidget)
        self.btnFechar.setGeometry(QtCore.QRect(110, 220, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnFechar.setFont(font)
        self.btnFechar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnFechar.setStyleSheet("border: none;\n"
"border-radius:10px;\n"
"background-color: rgb(53, 119, 218);\n"
"color: rgb(255, 255, 255);")
        self.btnFechar.setObjectName("btnFechar")
        ConfirmarPagamento.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ConfirmarPagamento)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 300, 22))
        self.menubar.setObjectName("menubar")
        ConfirmarPagamento.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ConfirmarPagamento)
        self.statusbar.setObjectName("statusbar")
        ConfirmarPagamento.setStatusBar(self.statusbar)

        self.retranslateUi(ConfirmarPagamento)
        QtCore.QMetaObject.connectSlotsByName(ConfirmarPagamento)

    def retranslateUi(self, ConfirmarPagamento):
        _translate = QtCore.QCoreApplication.translate
        ConfirmarPagamento.setWindowTitle(_translate("ConfirmarPagamento", "Sistema de estacionamento - Confirmação do pagamento"))
        self.label.setText(_translate("ConfirmarPagamento", "Pagamento confirmado!"))
        self.label_2.setText(_translate("ConfirmarPagamento", "O pagamento foi\n"
" efetuado com\n"
" sucesso!"))
        self.btnFechar.setText(_translate("ConfirmarPagamento", "Fechar"))
