# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './docs/login.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.setEnabled(True)
        Login.resize(900, 600)
        Login.setMinimumSize(QtCore.QSize(900, 600))
        Login.setMaximumSize(QtCore.QSize(900, 600))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./docs/../../../../../.designer/backup/imagens/seguro-de-automovel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Login.setWindowIcon(icon)
        Login.setStyleSheet("background-color: rgb(229, 229, 229);")
        self.centralwidget = QtWidgets.QWidget(Login)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 100, 901, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(75, 74, 74);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.nome_usuario = QtWidgets.QLineEdit(self.centralwidget)
        self.nome_usuario.setGeometry(QtCore.QRect(290, 170, 321, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.nome_usuario.setFont(font)
        self.nome_usuario.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 11pt \"Segoe UI\";\n"
"padding-left: 40px;\n"
"border-radius:10px;\n"
"color: rgb(75, 74, 74);")
        self.nome_usuario.setText("")
        self.nome_usuario.setObjectName("nome_usuario")
        self.senha_usuario = QtWidgets.QLineEdit(self.centralwidget)
        self.senha_usuario.setEnabled(True)
        self.senha_usuario.setGeometry(QtCore.QRect(290, 220, 321, 41))
        self.senha_usuario.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 11pt \"Segoe UI\";\n"
"padding-left: 40px;\n"
"border-radius:10px;\n"
"color: rgb(75, 74, 74);")
        self.senha_usuario.setEchoMode(QtWidgets.QLineEdit.Password)
        self.senha_usuario.setObjectName("senha_usuario")
        self.btnEntrar = QtWidgets.QPushButton(self.centralwidget)
        self.btnEntrar.setGeometry(QtCore.QRect(290, 320, 321, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnEntrar.setFont(font)
        self.btnEntrar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnEntrar.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(53, 119, 218);\n"
"border: none;\n"
"border-radius:10px;")
        self.btnEntrar.setObjectName("btnEntrar")
        self.btnCadastrar = QtWidgets.QPushButton(self.centralwidget)
        self.btnCadastrar.setGeometry(QtCore.QRect(380, 370, 131, 20))
        self.btnCadastrar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnCadastrar.setStyleSheet("color: rgb(53, 119, 218);\n"
"border:none;")
        self.btnCadastrar.setObjectName("btnCadastrar")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(310, 220, 21, 41))
        self.label_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("./docs/imagens/cadeado16.png"))
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(310, 170, 21, 41))
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("./docs/imagens/user16.png"))
        self.label_2.setObjectName("label_2")
        self.frameErro = QtWidgets.QFrame(self.centralwidget)
        self.frameErro.setGeometry(QtCore.QRect(180, 399, 541, 51))
        self.frameErro.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameErro.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameErro.setObjectName("frameErro")
        self.loginIncorreto = QtWidgets.QLabel(self.frameErro)
        self.loginIncorreto.setGeometry(QtCore.QRect(0, 9, 541, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.loginIncorreto.setFont(font)
        self.loginIncorreto.setStyleSheet("color: rgb(255, 0, 0);")
        self.loginIncorreto.setText("")
        self.loginIncorreto.setAlignment(QtCore.Qt.AlignCenter)
        self.loginIncorreto.setObjectName("loginIncorreto")
        self.btnFecharFrameErro = QtWidgets.QPushButton(self.frameErro)
        self.btnFecharFrameErro.setGeometry(QtCore.QRect(520, 0, 21, 16))
        self.btnFecharFrameErro.setStyleSheet("background-color: rgb(224, 27, 36);")
        self.btnFecharFrameErro.setObjectName("btnFecharFrameErro")
        self.radioButtonCliente = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButtonCliente.setGeometry(QtCore.QRect(290, 270, 112, 23))
        self.radioButtonCliente.setObjectName("radioButtonCliente")
        self.radioButtonFuncionario = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButtonFuncionario.setGeometry(QtCore.QRect(290, 290, 112, 23))
        self.radioButtonFuncionario.setObjectName("radioButtonFuncionario")
        self.label.raise_()
        self.nome_usuario.raise_()
        self.senha_usuario.raise_()
        self.btnEntrar.raise_()
        self.btnCadastrar.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.frameErro.raise_()
        self.radioButtonCliente.raise_()
        self.radioButtonFuncionario.raise_()
        Login.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Login)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 900, 22))
        self.menubar.setObjectName("menubar")
        Login.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Login)
        self.statusbar.setObjectName("statusbar")
        Login.setStatusBar(self.statusbar)

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Sistema de estacionamento - Login"))
        self.label.setText(_translate("Login", "Sistema de estacionamento"))
        self.nome_usuario.setPlaceholderText(_translate("Login", "Nome de usuário"))
        self.senha_usuario.setPlaceholderText(_translate("Login", "Senha"))
        self.btnEntrar.setText(_translate("Login", "Entrar"))
        self.btnCadastrar.setText(_translate("Login", "Cadastre-se"))
        self.btnFecharFrameErro.setText(_translate("Login", "X"))
        self.radioButtonCliente.setText(_translate("Login", "Cliente"))
        self.radioButtonFuncionario.setText(_translate("Login", "Funcionário"))
